### ISSUE TITLE
The alignment between EOReader and SNAP

### ISSUE THREAD

**Issue by TK12331** [sertit/eoreader#66] opened 2022-12-01 16:24 UTC
I process Sentinel-1 data with SNAP before, and now I want to align the processing results between EOReader and SNAP. 
I process GRD product using EOReader with step: 
`Apply-Orbit-File` -> `ThermalNoiseRemoval` -> `Remove-GRD-Border-Noise` -> `Calibration `-> `Terrain-Correction`. (for comparing the value of pixel, I remove step `LinearToFromdB` currently.

The name of the GRD product I use is S1A_IW_GRDH_1SDV_20200308T121318_20200308T121343_031584_03A39B_5C41.zip, whose image shape is 25847 x 16731.

However, I found some problems as followes:
1. Comparation between`Calibration` product
The value of tif file I generated from SNAP is 0-255(float64,but all the decimal value is 0), while the value of tif file I generated from EOReader is 0-123.4(float32). Besides, the scale value between corresponding pixels is not constant.

2. Comparation between `Terrain-Correction` product
The value problem is as same as 1. 
The shape of tif file I generated from SNAP is 31668 x 21478, while the shape  of tif file I generated from EOReader is 14372 x 10790.

Why they aren't alignment? Or am I missing something?

In addition, can the  step  of `Remove-GRD-Border-Noise`  and `ThermalNoiseRemoval` be swapped?

**Comment by remi-braun** [comment] 2022-12-01 18:32
Duplicate of #65

**Closed by remi-braun** 2022-12-01 18:32 UTC
Labels: bug
